# -*- coding: utf-8 -*-
"""Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3dnq5zFWZw6G6_4p9o6rpTPMtMuRy1d
"""

# Importing required libraries
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
anime = pd.read_csv("anime.csv")

# Display first few records
anime.head()

# Check basic info
anime.info()

# Check missing values
anime.isnull().sum()

# Display dataset shape
print("Dataset Shape:", anime.shape)

# Fill missing values in categorical and numerical columns
anime['genre'] = anime['genre'].fillna("Unknown")
anime['rating'] = anime['rating'].fillna(anime['rating'].mean())
anime['type'] = anime['type'].fillna("Unknown")

# Clean the 'episodes' column safely
# Convert non-numeric values to NaN
anime['episodes'] = pd.to_numeric(anime['episodes'], errors='coerce')

# Replace NaN values with median
anime['episodes'] = anime['episodes'].fillna(anime['episodes'].median())

# Drop duplicates if any
anime.drop_duplicates(inplace=True)

# Confirm cleaning
anime.isnull().sum()

# Combine genre and rating features
anime['combined_features'] = anime['genre'] + " " + anime['type']

# Convert to TF-IDF representation
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(anime['combined_features'])

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

print("Cosine similarity matrix shape:", cosine_sim.shape)

# Create a function to recommend similar anime
def recommend_anime(title, cosine_sim=cosine_sim):
    if title not in anime['name'].values:
        print("Anime not found in database.")
        return

    idx = anime[anime['name'] == title].index[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]  # Top 10 recommendations

    anime_indices = [i[0] for i in sim_scores]
    return anime[['name', 'genre', 'type']].iloc[anime_indices]

# Example
recommend_anime("Naruto")

# Split the dataset (conceptual evaluation)
train, test = train_test_split(anime, test_size=0.2, random_state=42)

# Compute similarity on training set
train_tfidf = tfidf.fit_transform(train['combined_features'])
train_sim = cosine_similarity(train_tfidf)

# Dummy precision/recall illustration
precision = 0.85
recall = 0.80
f1 = 2 * (precision * recall) / (precision + recall)

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {round(f1,2)}")

